---
title: "National Walkabliity Index Data Cleaning"
author: "Vanessa Veto  // Sean Leader William Medwid // Jose Mierzejewski"
format: 
  html:
    code-fold: true
    code-line-numbers: true
    code-tools: true
    self-contained: true
editor: visual
execute:
  message: false
---

# Libraries + Data

```{r packages, message = FALSE}
library(tidyverse)
library(here)
```

```{r dataset loading, message = FALSE}
nwi <- read_csv(here("EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv"))
fips <- read_csv(here("FIPS Code.csv"))
```

```{r}
nwi <- nwi %>% 
  left_join(fips, by = c("STATEFP" = "Code"))
```

```{r}
nwi <- nwi %>% drop_na(CBSA_Name)

# remove places where no GTFS service data
nwi <- nwi[nwi$D4E != -99999, ]  
nwi <- nwi[nwi$D5BR != -99999, ]  
nwi <- nwi[nwi$D5BE != -99999, ]  

#nwi$state = gsub(".*,", "", nwi$CBSA_Name)
nwi$CBG = gsub(",.*$", "", nwi$CBSA_Name)

nwi$cat <- ifelse(nwi$NatWalkInd >= 15.26, 'Most walkable', 
       ifelse(nwi$NatWalkInd >= 10.51 & nwi$NatWalkInd < 15.26, 'Above average walkable', 
              ifelse(nwi$NatWalkInd >= 5.76 & nwi$NatWalkInd < 10.51, 'Below average walkable', ifelse(nwi$NatWalkInd >=1 & nwi$NatWalkInd < 5.76, 'Least walkable', 'other'))
             )
       )

nwi$cat <- factor(nwi$cat,
                levels = c("Least walkable", "Below average walkable", 'Above average walkable', 'Most walkable'))
```

```{r}
# 1 if population-weighted centroid within .75 miles from a transit stop, 0 otherwise
nwi$Ind_D4A <- ifelse(nwi$D4A != -99999, 1, 0)

# -99999 means there is no transit service, so recode Aggregate Frequency of Peak Hour Transit Service to zero for these areas
nwi$D4C <- ifelse(nwi$D4C == -99999, 0, nwi$D4C)

# no transit service recodes to zero
nwi$Ind_D4D <- ifelse(nwi$D4D == -99999, 0, nwi$D4D)

nwi %>% summary
```

```{r}
ggplot(nwi, aes(x=cat)) + geom_bar(stat="count") + xlab('Walkability Index Category') + ylab('Frequency') + labs(title='Barplot of Walkability Index Categories')

ggplot(nwi, 
       aes(x = cat, 
           y = D3B)) +
  geom_boxplot() +
  labs(title = "Street intersection density distribution by category")

ggplot(nwi, 
       aes(x = cat, 
           y = CBSA_POP)) +
  geom_boxplot() +
  labs(title = "Population distribution by category")


ggplot(nwi, 
       aes(x = cat, 
           y = Ac_Total)) +
  geom_boxplot() +
  labs(title = "Total Area distribution by category")

qtr_pct_lowwage <- ifelse(nwi$R_PCTLOWWAGE >= .25, 'Yes', 'No')
ggplot(nwi, aes(x=cat, fill=majority_pct_lowwage)) + geom_bar(stat="count") + xlab('Walkability Index Category') + ylab('Frequency') + labs(title='Barplot of Walkability Index Categories') + guides(fill=guide_legend(title="Over 25% of Population Low Wage Workers"))


# Plot mix of employment types
ggplot(nwi, 
       aes(x = D2B_E8MIXA, 
           y = NatWalkInd, color = cat)) +
  geom_point(size = 1)


# Plot  mix of employment types and occupied housing
ggplot(nwi, 
       aes(x = D2A_EPHHM, 
           y = NatWalkInd, color = cat)) +
  geom_point(size = 1)

# plot meadian population by NWI category
plotdata <- nwi %>%
  group_by(cat) %>%
  summarize(med_pop = median(CBSA_POP))

ggplot(plotdata, 
       aes(x = cat, 
           y = med_pop)) +
  geom_bar(stat = "identity")

# plot median total area by NWI category
plotdata <- nwi %>%
  group_by(cat) %>%
  summarize(med_area = median(Ac_Total))

ggplot(plotdata, 
       aes(x = cat, 
           y = med_area)) +
  geom_bar(stat = "identity")


# plot median percent of zero-car households
plotdata <- nwi %>%
  group_by(cat) %>%
  summarize(med_pct_no_car = median(Pct_AO0))

ggplot(plotdata, 
       aes(x = cat, 
           y = med_pct_no_car)) +
  geom_bar(stat = "identity")

# plot median percent of two-plus-car households
plotdata <- nwi %>%
  group_by(cat) %>%
  summarize(med_pct_no_car = median(Pct_AO2p))

ggplot(plotdata, 
       aes(x = cat, 
           y = med_pct_no_car)) +
  geom_bar(stat = "identity")
```
